name: Image Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64

    name: Create (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AC_DOCKER_USERNAME }}
          password: ${{ secrets.AC_DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build --tag activeclass/php:${{ env.VERSION }}-${{ matrix.arch }} .

      - name: Push Docker Image
        if: github.event_name == 'push'
        run: |
          docker push activeclass/php:${{ env.VERSION }}-${{ matrix.arch }}
  update-manifest:
    name: Push Docker Manifest
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AC_DOCKER_USERNAME }}
          password: ${{ secrets.AC_DOCKER_PASSWORD }}

      - name: Create and Push Docker Manifest
        if: github.event_name == 'push'
        run: |
          docker manifest create \
            activeclass/php:${{ env.VERSION }} \
            --amend activeclass/php:${{ env.VERSION }}-arm64 \
            --amend activeclass/php:${{ env.VERSION }}-amd64

          docker manifest push activeclass/php:${{ env.VERSION }}

